from __future__ import annotations

import shutil
import zipfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


def as_int(value: Any) -> int:
    try:
        if value is None or value == "":
            return 0
        return int(float(str(value).replace(",", "").strip()))
    except Exception:
        return 0


def compact(value: Any) -> str:
    n = as_int(value)
    if abs(n) >= 1_000_000:
        return f"{n / 1_000_000:.1f}M".replace(".0M", "M")
    if abs(n) >= 1_000:
        return f"{n / 1_000:.1f}k".replace(".0k", "k")
    return f"{n:,}"


@dataclass
class LibraryStats:
    projects: int
    videos: int
    transcripts: int
    words: int
    missing: int
    zip_ready: int


@dataclass
class BundleResult:
    bundle_path: Path
    prompt_path: Path
    readme_path: Path
    included_zips: list[Path]
    skipped_projects: list[str]


def summarize(projects: list[dict[str, Any]]) -> LibraryStats:
    return LibraryStats(
        projects=len(projects),
        videos=sum(as_int(p.get("videos_found")) for p in projects),
        transcripts=sum(as_int(p.get("transcripts_created")) for p in projects),
        words=sum(as_int(p.get("total_words")) for p in projects),
        missing=sum(as_int(p.get("missing_subtitles")) for p in projects),
        zip_ready=sum(1 for p in projects if p.get("zip_path") and Path(str(p.get("zip_path"))).exists()),
    )


def density(project: dict[str, Any]) -> int:
    transcripts = as_int(project.get("transcripts_created"))
    words = as_int(project.get("total_words"))
    return int(words / transcripts) if transcripts else 0


def strength(project: dict[str, Any]) -> str:
    words = as_int(project.get("total_words"))
    transcripts = as_int(project.get("transcripts_created"))
    if transcripts >= 100 and words >= 150_000:
        return "Deep library"
    if transcripts >= 50 and words >= 75_000:
        return "Strong library"
    if transcripts >= 30:
        return "Useful library"
    return "Small pack"


def ranked_projects(projects: list[dict[str, Any]]) -> list[dict[str, Any]]:
    items = []
    for p in projects:
        item = dict(p)
        item["_density"] = density(item)
        item["_strength"] = strength(item)
        items.append(item)
    return sorted(items, key=lambda p: as_int(p.get("total_words")), reverse=True)


def generate_prompt(projects: list[dict[str, Any]], focus: str) -> str:
    stats = summarize(projects)
    ranked = ranked_projects(projects)
    rows = []
    for p in ranked:
        rows.append(
            f"- {p.get('name', 'Unnamed')}: "
            f"{as_int(p.get('videos_found'))} videos, "
            f"{as_int(p.get('transcripts_created'))} transcripts, "
            f"{as_int(p.get('total_words')):,} words, "
            f"strength={strength(p)}, "
            f"ZIP={p.get('zip_path', '-')}"
        )

    focus = focus.strip() or "Compare all uploaded YTIS packs for business lessons, workflows, service ideas, pricing, offers, and sales patterns."

    return f"""# YTIS Multi-Project Analysis Prompt

You are analyzing multiple YouTube transcript research packs generated by YTIS.

Library context:
- Projects: {stats.projects}
- Videos: {stats.videos}
- Transcripts: {stats.transcripts}
- Total words: {stats.words:,}
- Missing subtitles: {stats.missing}
- ZIP-ready projects: {stats.zip_ready}

Projects:
{chr(10).join(rows)}

Analysis focus:
{focus}

Instructions:
- Use the uploaded ZIP files as the primary source.
- Compare the projects/channels against each other.
- Identify repeated advice across multiple creators.
- Separate common advice from unique advice.
- Prefer concrete workflows, examples, service ideas, offer/pricing logic, sales processes, and operational systems.
- Be skeptical of generic creator advice.
- Do not invent facts that are not supported by the transcripts.
- Reference source project/channel names when possible.

Output format:
1. Executive summary.
2. Project-by-project comparison table.
3. Strongest repeated lessons across all projects.
4. Unique or contradictory lessons.
5. Workflow inventory across the library.
6. Offer/pricing/service ideas relevant to Rafael Alba and Webify Digital Solutions.
7. What to ignore or verify.
8. Practical 30-day action plan.
"""


def save_prompt(text: str, downloads_dir: Path) -> Path:
    path = downloads_dir / f"YTIS_MULTI_PROJECT_PROMPT_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path.write_text(text, encoding="utf-8")
    return path


def create_library_upload_bundle(projects: list[dict[str, Any]], focus: str, downloads_dir: Path) -> BundleResult:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    bundle_root = downloads_dir / f"YTIS_LIBRARY_UPLOAD_BUNDLE_{stamp}"
    bundle_root.mkdir(parents=True, exist_ok=True)

    prompt_text = generate_prompt(projects, focus)
    prompt_path = bundle_root / "YTIS_MULTI_PROJECT_ANALYSIS_PROMPT.md"
    prompt_path.write_text(prompt_text, encoding="utf-8")

    stats = summarize(projects)
    zip_dir = bundle_root / "research_packs"
    zip_dir.mkdir(parents=True, exist_ok=True)

    included: list[Path] = []
    skipped: list[str] = []

    for project in ranked_projects(projects):
        name = str(project.get("name", "Unnamed"))
        zip_value = project.get("zip_path")
        if not zip_value:
            skipped.append(f"{name}: no ZIP path")
            continue
        src = Path(str(zip_value))
        if not src.exists():
            skipped.append(f"{name}: ZIP missing")
            continue
        safe_name = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in name).strip("_") or "project"
        dst = zip_dir / f"{safe_name}__{src.name}"
        shutil.copy2(src, dst)
        included.append(dst)

    readme = bundle_root / "README_UPLOAD_THIS_BUNDLE.md"
    readme.write_text(
        f"""# YTIS Library Upload Bundle

Created: {stamp}

Library summary:
- Projects in registry: {stats.projects}
- ZIP-ready projects copied: {len(included)}
- Videos: {stats.videos}
- Transcripts: {stats.transcripts}
- Words: {stats.words:,}
- Missing subtitles: {stats.missing}

How to use:
1. Upload this whole bundle ZIP to ChatGPT, or upload the ZIP files inside `research_packs`.
2. Open `YTIS_MULTI_PROJECT_ANALYSIS_PROMPT.md`.
3. Paste the prompt after uploading the research packs.
4. Ask ChatGPT to use the uploaded files as the primary source.

Included research packs:
{chr(10).join(f"- {p.name}" for p in included) or "- None"}

Skipped:
{chr(10).join(f"- {item}" for item in skipped) or "- None"}
""",
        encoding="utf-8",
    )

    bundle_zip = downloads_dir / f"YTIS_LIBRARY_UPLOAD_BUNDLE_{stamp}.zip"
    with zipfile.ZipFile(bundle_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in bundle_root.rglob("*"):
            if path.is_file():
                zf.write(path, path.relative_to(bundle_root))

    return BundleResult(
        bundle_path=bundle_zip,
        prompt_path=prompt_path,
        readme_path=readme,
        included_zips=included,
        skipped_projects=skipped,
    )
