from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any


def as_int(value: Any) -> int:
    try:
        if value is None or value == "":
            return 0
        return int(float(str(value).replace(",", "").strip()))
    except Exception:
        return 0


def compact(value: Any) -> str:
    n = as_int(value)
    if abs(n) >= 1_000_000:
        return f"{n / 1_000_000:.1f}M".replace(".0M", "M")
    if abs(n) >= 1_000:
        return f"{n / 1_000:.1f}k".replace(".0k", "k")
    return f"{n:,}"


@dataclass
class LibraryStats:
    projects: int
    videos: int
    transcripts: int
    words: int
    missing: int
    zip_ready: int


def summarize(projects: list[dict[str, Any]]) -> LibraryStats:
    return LibraryStats(
        projects=len(projects),
        videos=sum(as_int(p.get("videos_found")) for p in projects),
        transcripts=sum(as_int(p.get("transcripts_created")) for p in projects),
        words=sum(as_int(p.get("total_words")) for p in projects),
        missing=sum(as_int(p.get("missing_subtitles")) for p in projects),
        zip_ready=sum(1 for p in projects if p.get("zip_path")),
    )


def density(project: dict[str, Any]) -> int:
    transcripts = as_int(project.get("transcripts_created"))
    words = as_int(project.get("total_words"))
    return int(words / transcripts) if transcripts else 0


def strength(project: dict[str, Any]) -> str:
    words = as_int(project.get("total_words"))
    transcripts = as_int(project.get("transcripts_created"))
    if transcripts >= 100 and words >= 150_000:
        return "Deep library"
    if transcripts >= 50 and words >= 75_000:
        return "Strong library"
    if transcripts >= 30:
        return "Useful library"
    return "Small pack"


def ranked_projects(projects: list[dict[str, Any]]) -> list[dict[str, Any]]:
    items = []
    for p in projects:
        item = dict(p)
        item["_density"] = density(item)
        item["_strength"] = strength(item)
        items.append(item)
    return sorted(items, key=lambda p: as_int(p.get("total_words")), reverse=True)


def generate_prompt(projects: list[dict[str, Any]], focus: str) -> str:
    stats = summarize(projects)
    ranked = ranked_projects(projects)
    rows = []
    for p in ranked:
        rows.append(
            f"- {p.get('name', 'Unnamed')}: "
            f"{as_int(p.get('videos_found'))} videos, "
            f"{as_int(p.get('transcripts_created'))} transcripts, "
            f"{as_int(p.get('total_words')):,} words, "
            f"strength={strength(p)}, "
            f"ZIP={p.get('zip_path', '-')}"
        )

    focus = focus.strip() or "Compare all uploaded YTIS packs for business lessons, workflows, service ideas, pricing, offers, and sales patterns."

    return f"""# YTIS Multi-Project Analysis Prompt

You are analyzing multiple YouTube transcript research packs generated by YTIS.

Library context:
- Projects: {stats.projects}
- Videos: {stats.videos}
- Transcripts: {stats.transcripts}
- Total words: {stats.words:,}
- Missing subtitles: {stats.missing}
- ZIP-ready projects: {stats.zip_ready}

Projects:
{chr(10).join(rows)}

Analysis focus:
{focus}

Instructions:
- Use the uploaded ZIP files as the primary source.
- Compare the projects/channels against each other.
- Identify repeated advice across multiple creators.
- Separate common advice from unique advice.
- Prefer concrete workflows, examples, service ideas, offer/pricing logic, sales processes, and operational systems.
- Be skeptical of generic creator advice.
- Do not invent facts that are not supported by the transcripts.
- Reference source project/channel names when possible.

Output format:
1. Executive summary.
2. Project-by-project comparison table.
3. Strongest repeated lessons across all projects.
4. Unique or contradictory lessons.
5. Workflow inventory across the library.
6. Offer/pricing/service ideas relevant to Rafael Alba and Webify Digital Solutions.
7. What to ignore or verify.
8. Practical 30-day action plan.
"""


def save_prompt(text: str, downloads_dir: Path) -> Path:
    path = downloads_dir / f"YTIS_MULTI_PROJECT_PROMPT_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    path.write_text(text, encoding="utf-8")
    return path
